### ISSUE TITLE
Fatal error: Class 'BigTreeFacebookAPI' after installing

### ISSUE THREAD

**Issue by NickStees** [Fastspot/bigtree-social-feed#1]
After installing this and going to modules > social feed > add query

I get Fatal error: Class 'BigTreeFacebookAPI' not found in /public/extensions/com.fastspot.social-feed/modules/social-feed/_form.php on line 4

I don't see this class on the https://www.bigtreecms.org/docs/dev-guide/advanced/service-apis/ page either.

**Comment by timbuckingham** [comment]
The latest updates require BigTree 4.2.8 (currently in the 4.2-devel branch).

**Comment by NickStees** [comment]
So if I am running 4.2.7 what would you recommend me doing? Is there a way to grab an older version of this extension that is compatible with 4.2.7?

**Comment by timbuckingham** [comment]
Grab this version:
https://github.com/Fastspot/bigtree-social-feed/archive/c617455e985f8983602a3fe469ef385e4ec284b8.zip
